name: Regenerate BagIt checksums

on:
  workflow_call:

  workflow_dispatch:

concurrency:
  group: "commits"
  cancel-in-progress: false    

permissions:
  contents: write
  pages: write
  id-token: write      

jobs:
  bagit:
    runs-on: ubuntu-22.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create BagIt manifest for Example Request
        working-directory: 0.4-DRAFT/example-request 
        run: |
          rm -f manifest*txt tagmanifest*txt
          sha512sum `find data -type f` > manifest-sha512.txt
          sha512sum bag-info.txt bagit.txt manifest-sha512.txt > tagmanifest-sha512.txt

      - name: Create BagIt manifest for Example Result
        working-directory: 0.4-DRAFT/example-result 
        run: |
          rm -f manifest*txt tagmanifest*txt
          sha512sum `find data -type f` > manifest-sha512.txt
          sha512sum bag-info.txt bagit.txt manifest-sha512.txt > tagmanifest-sha512.txt

      - name: Create BagIt manifest for Example Hutch
        working-directory: 0.4-DRAFT/example-hutch 
        run: |
          rm -f manifest*txt tagmanifest*txt
          sha512sum `find data -type f` > manifest-sha512.txt
          sha512sum bag-info.txt bagit.txt manifest-sha512.txt > tagmanifest-sha512.txt  

      - name: Archive BagIts as ZIP
        working-directory: 0.4-DRAFT/
        run: |
          rm -f *.zip
          zip -r example-request.bagit.zip example-request/
          zip -r example-result.bagit.zip example-result/          
          
      - name: Commit manifests
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          files: |
            0.4-DRAFT/example-request/manifest-sha512.txt
            0.4-DRAFT/example-request/tagmanifest-sha512.txt
            0.4-DRAFT/example-result/manifest-sha512.txt
            0.4-DRAFT/example-result/tagmanifest-sha512.txt
            0.4-DRAFT/example-request.bagit.zip
            0.4-DRAFT/example-result.bagit.zip
          commit-message: |
            Updated BagIt manifests
            
      - name: Get new git commit
        id: sha
        run: |
              sha_new=$(git rev-parse HEAD)
              echo $sha_new
              echo "::set-output name=SHA::$sha_new"
      - name: New commit
        run:
          echo ${{ steps.sha.outputs.SHA }}            
      