name: Regenerate BagIt checksums

on:
  push:
    paths:
      - '**/example*/**'
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write      

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04    

    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create BagIt manifest for Example Request
        working-directory: 0.3-DRAFT/example-request 
        run: |
          rm manifest*txt tagmanifest*txt
          sha512sum `find data -type f` > manifest-sha512.txt
          sha512sum bag-info.txt bagit.txt manifest-sha512.txt > tagmanifest-sha512.txt

      - name: Create BagIt manifest for Example Result
        working-directory: 0.3-DRAFT/example-result 
        run: |
          rm manifest*txt tagmanifest*txt
          sha512sum `find data -type f` > manifest-sha512.txt
          sha512sum bag-info.txt bagit.txt manifest-sha512.txt > tagmanifest-sha512.txt

      - name: Archive BagIts as ZIP
        working-directory: 0.3-DRAFT/
        run: |
          rm *.zip
          zip -r example-request.bagit.zip example-request/
          zip -r example-result.bagit.zip example-result/
          
      - name: Commit manifests
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          files: |
            0.3-DRAFT/example-request/manifest-sha512.txt
            0.3-DRAFT/example-request/tagmanifest-sha512.txt
            0.3-DRAFT/example-result/manifest-sha512.txt
            0.3-DRAFT/example-result/tagmanifest-sha512.txt
            example-request.bagit.zip
            example-result.bagit.zip
          commit-message: |
            Updated BagIt manifests
      
      - name: Deploy using Jekyll
        uses: ./.github/workflows/jekyll-gh-pages-workflow-call.yml