name: Generate RO-Crate preview
on:
  push:
    paths:
      - '**/ro-crate-metadata.json'
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: RO Crate Preview for Profile Crate
        uses: ResearchObject/ro-crate-preview-action@v1.3.0
        with:
          crate_path: 0.3-DRAFT
        
      - name: RO Crate Preview for Example Request
        uses: ResearchObject/ro-crate-preview-action@v1.3.0
        with:
          crate_path: 0.3-DRAFT/example-request

      - name: RO Crate Preview for Example Result
          uses: ResearchObject/ro-crate-preview-action@v1.3.0
          with:
            crate_path: 0.3-DRAFT/example-result
          
      - name: Commit RO Crate Preview
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          files: |
            0.3-DRAFT/ro-crate-preview.html
            0.3-DRAFT/example-request/ro-crate-preview.html
            0.3-DRAFT/example-result/ro-crate-preview.htm
          commit-message: |
            Updated RO-Crate preview